[project]
name = "poap-project"
description = "Proof of Attendance Protocol (POAP) built with Clarity"
authors = ["Your Name <you@example.com>"]

[contracts.sip009-trait]
path = "contracts/sip009-trait.clar"

[contracts.poap-nft]
path = "contracts/poap-nft.clar"

[contracts.poap-minter]
path = "contracts/poap-minter.clar"
